@startuml
start
:获取规则标识及配置;
:获取有效投标单位数量N, 入围总人数M;
if (N <= M?) then (是)
    :新建一轮“入围”;
    :标记为“因人数不足转自动全部入围”;
    :所有有效单位标记为“已入围”;
    :标记本轮为“已完成”，不可编辑;
    :前端展示全入围列表;
    :代理点击“完成确定入围”按钮;
    stop
else (否)
    if (配置满足“固定人数”?) then (是)
        if (配置满足“固定轮数”?) then (是)
            :初始化当前轮数=1;
            while (当前轮数 <= 固定总轮数?)
                :新建第N轮入围;
                :初始化当前所有未入围单位为“未入围”;
                :前端展示，代理勾选X人;
                :点击“确认本轮入围名单”;
                :标记本轮“已完成”;
                :当前轮数+1;
                :总入围人数累计;
            endwhile
        else (否)
            :初始化总入围累计人数=0;
            while (总入围累计人数 < M?)
                :新建一轮入围;
                :初始化当前所有未入围单位为“未入围”;
                :前端展示，代理勾选至少1人;
                :点击“确认本轮入围名单”;
                :总入围累计人数 += 本轮勾选人数;
                if (总入围累计人数 == M?) then (是)
                    break
                else (否)
                    :准备下一轮(扣除已入围);
                endif
            endwhile
        endif
    else (否)
        :新建唯一一轮入围;
        :初始化所有单位为“未入围”;
        :前端展示，代理勾选至少1人;
        :点击“确认本轮入围名单”;
    endif

    :进入“推荐入围”逻辑;

    :初始化推荐入围单位\n(总单位-已入围单位);
    :新建一轮“推荐入围”;
    if (代理点击“跳过”?) then (是)
        :跳过推荐;
    else (否)
        if (配置母表人数不为空?) then (是)
            :代理可选择[1, 给定人数]家;
            :至多选满给定人数后确认;
        else (否)
            :代理可选择[1, 剩余人数]家;
            :至少选1家后确认;
        endif
        :推荐入围完成;
    endif

    :进入“候补”逻辑;
    :初始化候补单位\n(总-已入围-已推荐);
    :新建一轮“候补”;
    if (配置母表人数不为空?) then (是)
        :代理可选择[1, 给定人数]家;
        :至多选满给定人数后确认;
    else (否)
        :代理可选择[1, 剩余人数]家;
        :至少选1家后确认;
    endif
    :候补完成;
    :代理点击“完成确定入围”按钮;
    stop
endif
@enduml