@startuml
|业务中台|
start
:保存暗标规则;
:调用配置服务保存暗标规则信息接口;
|配置服务|
:根据规则生成二进制文件;
:文件上传至文件服务器;
:记录文件id、设定的maxI、maxY值，与暗标规则一同入库;
|业务中台|
:调用结束;

|开标服务|
:开标结束时发送MQ消息;
|评标服务|
:接收开标结束消息，初始化redis缓存池;
:startflow，每个服务节点均初始化缓冲池;
:进入暗标步骤;
|暗标组件|
:进入按评审条款/评审因素关联逻辑;
:实时生成该步骤需要的暗标编码;
:按照四个维度的配置将暗标编码关联到投标单位上;
:关联结果入库;
|评标服务|
:调用结束;

|页面|
:调用查询接口查询页面内容;
|评标服务|
:返回查询结果;
stop
@enduml
