@startuml
|页面|
start
:进入B值抽取页面;
:点击开始抽取;

|开标App|
:通过paramExtract client调用;

|评标服务|
:根据callStage判断调用方;
if (判断标段状态) then (状态处于开标中)
    |项目服务|
    :开始执行算法流程;
else (状态处于评标中)
    |计算服务|
    :开始执行算法流程;
endif
|开标App|
:计算出B值抽取范围，忽略计算出的错误得分;

|页面|
:在前端完成B值抽取;

|开标App|
:通过paramExtract client调用;

|评标服务|
:保存B值入库;
if (标段状态处于评标中) then (是)
    |计算服务|
    :计算得分;
    :发送消息给评标前端，刷新页面;
else (否)
endif

|开标App|
:B值抽取完成;
stop
@enduml
